services:
  - type: web
    name: cashfree-payment-app
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CASHFREE_CLIENT_ID
        sync: false
      - key: CASHFREE_CLIENT_SECRET
        sync: false
      - key: CASHFREE_ENV
        value: production
